### ISSUE TITLE
Implement tournament selection 

### ISSUE THREAD

**Issue by piotr-muzyka** [pawel-jakubowski/NSGA#13]
The way to implement Tournament selection in NSGA .
The selection of individuals to the mating pool is based on the tournament selection method. 
N individuals are selected at random (at first I'd go with n=2), from the selected individuals only one individual is selected and added to mating pool. The selection is based on two criteria's :
1. Rank or the solution front  (lower rank individual is selected),

If ranks are equal we use the second criteria
2. Crowding distance comparison (individual with greater distance is selected to the mating pool). 

The tournament selection is performed until the mating pool is filled with individuals.

**Comment by pawel-jakubowski** [comment]
> The selection is based on two criteria's :
> 1. Rank or the solution front (lower rank individual is selected),
> 
> If ranks are equal we use the second criteria
> 2. Crowding distance comparison (individual with greater distance is selected to the mating pool). 

You described exactly how _crowded distance operator_ works (and it's already implemented):

``` c++
bool Subject::operator<(const Subject &r)
{
    if(nondominationRank == r.nondominationRank)
        return crowdingDistance > r.crowdingDistance;
    else
        return nondominationRank < r.nondominationRank;
}
```

So if you want to use it just use something like:

``` c++
Subject subjectA, subjectB;
(...)
if (subjectA < subjectB)
(...)
```
