### ISSUE TITLE
Create genotype class

### ISSUE THREAD

**Issue by pawel-jakubowski** [pawel-jakubowski/NSGA#8]
Genotype should contain coding information and crossing method.

What do you think - we should code gens with binary or real numbers?

**Comment by piotr-muzyka** [comment]
After reading through several publications I am of the belief that we should code gens with real numbers - preferably using mixed-variable optimization as based on several studies it proved to identify better solutions than the binary approach. However I am concerned that such choice might  significantly increase the overall workload. 

![2](https://cloud.githubusercontent.com/assets/11503803/7216705/0b1dbcbe-e608-11e4-9690-19d7bcb48321.jpg)
![4](https://cloud.githubusercontent.com/assets/11503803/7216707/0b25da2a-e608-11e4-9158-3639d04c1d72.jpg)
 ![3](https://cloud.githubusercontent.com/assets/11503803/7216706/0b245ccc-e608-11e4-8261-0b870b01fc6d.jpg)
 ![1](https://cloud.githubusercontent.com/assets/11503803/7216704/0b186548-e608-11e4-8013-bb594ed7160a.jpg)

**Comment by pawel-jakubowski** [comment]
I don't get idea from given slides. It is clear that for this specify problem mixed coding is better but how exactly it works?

**Comment by pawel-jakubowski** [comment]
So we choose to code gens as real numbers
